[alias]
rr = "run --release"

# [build]
# # cargo install sccache
# rustc-wrapper = "/path/to/sccache"

# [http]
# proxy = "host:port"

[source.crates-io]
replace-with = 'tuna'

# 阿里云
[source.aliyun]
registry = "sparse+https://mirrors.aliyun.com/crates.io-index/"

# 中国科学技术大学
[source.ustc]
#registry = "https://mirrors.ustc.edu.cn/crates.io-index"
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index"

# 上海交通大学
[source.sjtu]
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/"

# 清华大学
[source.tuna]
#registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

# rustcc社区
[source.rustcc]
registry = "https://code.aliyun.com/rustcc/crates.io-index.git"

[source.rsproxy]
# registry = "https://rsproxy.cn/crates.io-index"
registry = "sparse+https://rsproxy.cn/index/"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[net]
git-fetch-with-cli = true